name: Maven release publish to package registry

on:
  release:
    types: [ published ]
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build and publish to GitHub Packages
      run: |
        cd api
        mvn deploy -s ${{ github.workspace }}/.m2/settings.xml
        cd ..
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USER: ${{ github.repository_owner }}
    - name: Generate JavaDoc
      run: |
        cd api
        mvn javadoc:javadoc
        cd ..
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}}}
        GITHUB_USER: ${{ github.repository_owner }}
    - name: Deploy JavaDoc
      uses: JamesIves/github-pages-deploy-action@v4.4.0
      with:
        token: ${{ secrets.SPECIAL_TOKEN }}}}
        branch: docs
        clean: true
        folder: api/target/site/apidocs
        target-folder: .
        name: ${{ github.repository_owner }}
        email: ${{ github.repository_owner }}@users.noreply.github.com
